CREATE TABLE [Schedules]
(
	[Id] [UNIQUEIDENTIFIER] NOT NULL,
	[UnitId] [UNIQUEIDENTIFIER] NOT NULL,
	[UnitName] [NVARCHAR](250) NOT NULL,
	[EmployeeId] [UNIQUEIDENTIFIER] NOT NULL,
	[EmployeeName] [NVARCHAR](250) NOT NULL,
	[StaffingRequirementId] [UNIQUEIDENTIFIER] NOT NULL,
	[StartTimeUtc] [DATETIMEOFFSET](7) NOT NULL,
	[ScheduledHours] [DECIMAL](18,2) NOT NULL,
	[ApprovedOnUtc] [DATETIMEOFFSET](7) NOT NULL,
	[CreatedBy] NVARCHAR (250) NOT NULL ,
	[UpdatedBy] NVARCHAR (250) NULL,
	[CreatedOnUtc] DATETIMEOFFSET NOT NULL DEFAULT GETUTCDATE(),
	[UpdatedOnUtc] DATETIMEOFFSET NULL,
	CONSTRAINT [PK_Schedules] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

