version: '3.8'
services: 
  db: 
    build: NurseCron.Employees.DB/. 
    ports: 
     - "1433:1433" 
#  api: 
#    build: src/NurseCron.Employees.api/. 
#    environment: 
#    - IdentityProvider=https://ikemtz.auth0.com/ 
#    - IdentityAudiences=NRSRx-Local-Docker 
#    - OAuthClientId=qTiPFgac8zPm04HVwgACMp7h2YbZ3451 
#    - OAuthAppName=NRSRx-Local-Docker (Swagger Client) 
#    - InstrumentationKey=310823a1-7fc9-40fa-be72-06ab32952e85 
#    - SqlConnectionString=Data Source=db;Initial Catalog=NRSRx;User ID=sa;Password=SqlDockerRocks123!; 
#    - CorsOrigin=http://localhost:4200 
#    ports: 
#    - "80:80" 
  odata:
    build: 
      context: ./
      dockerfile: ./Dev.OData.Dockerfile
  #    env_file:
  #    - src/NurseCron.Certifications.Api/Dockerfile.env
    ports:
    - "81:80"
  api:
    build: 
      context: ./
      dockerfile: ./Dev.WebApi.Dockerfile
  #    env_file:
  #    - src/NurseCron.Certifications.Api/Dockerfile.env
    ports:
    - "82:80"