using System;
using System.ComponentModel.DataAnnotations;
using IkeMtz.NRSRx.Core.Models;

namespace NurseCron.Services.Schedules.Abstraction
{
  // Generated by the SQL POCO Class Generator Script
  // Script is available at:
  // https://raw.githubusercontent.com/ikemtz/NRSRx/master/tools/sql-poco-class-generator.sql

  public partial class Schedule
  : IIdentifiable, IAuditable
  {
    [Required]
    public Guid Id { get; set; }
    [Required]
    public Guid UnitId { get; set; }
    [Required]
    [MaxLength(250)]
    public string UnitName { get; set; }
    [Required]
    public Guid EmployeeId { get; set; }
    [Required]
    [MaxLength(250)]
    public string EmployeeName { get; set; }
    [Required]
    public DateTimeOffset StartTimeUtc { get; set; }
    [Required]
    public decimal ScheduledHours { get; set; }
    [Required]
    public DateTimeOffset ApprovedOnUtc { get; set; }
    [Required]
    [MaxLength(250)]
    public string CreatedBy { get; set; }
    [MaxLength(250)]
    public string UpdatedBy { get; set; }
    [Required]
    public DateTimeOffset CreatedOnUtc { get; set; }
    public DateTimeOffset? UpdatedOnUtc { get; set; }
  }

}
