name: 1.$(Year:yy).$(DayOfYear)$(Rev:.rr)
resources:
  - repo: self
variables:
  DB_PROJECTS: '**/*.sqlproj'

jobs:
- job: Database
  displayName: Database build and deploy
  pool: Hosted Windows 2019 with VS2019

  steps:
  - task: SonarSource.sonarcloud.14d9cde6-c1da-4d55-aa01-2965cd301255.SonarCloudPrepare@1
    displayName: 'Prepare analysis on SonarCloud'
    inputs:
      SonarCloud: 'SonarCloud IkeMtz'
      organization: ikemtz
      projectKey: NurseCRON_Databases
      projectName: NurseCRON_Databases
      extraProperties: |
       # Additional properties that will be passed to the scanner, 
       # Put one key=value per line, example:
       # sonar.cs.vstest.reportsPaths=$(Agent.WorkFolder)/_temp/*.trx
       # sonar.branch.name=$(System.PullRequest.SourceBranch)
       # sonar.branch.target=$(System.PullRequest.TargetBranch)

  - task: VSBuild@1
    displayName: 'Build solution DB Project'
    inputs:
      solution: $(DB_PROJECTS)

  - task: SonarSource.sonarcloud.ce096e50-6155-4de8-8800-4221aaeed4a1.SonarCloudAnalyze@1
    displayName: 'Run Code Analysis'

  - task: SonarSource.sonarcloud.38b27399-a642-40af-bb7d-9971f69712e8.SonarCloudPublish@1
    displayName: 'Publish Quality Gate Result'

  - task: sonarcloud-buildbreaker@2
    displayName: 'Break build on SonarCloud quality gate failure'
    inputs:
      SonarCloud: 'SonarCloud IkeMtz'
      organization: 'ikemtz'

  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        Copy-Item "src/MicroServices/DB.Ci.Dockerfile" "$(build.artifactstagingdirectory)\" -Verbose -Force;
        Get-ChildItem $sourceFolder -Filter *.dacpac -Recurse | 
          Foreach-Object { 
            Write-Host "DacPac File: $($_.Name)";
            Copy-Item "$($_.FullName)" "$(build.artifactstagingdirectory)\" -Verbose -Force;
          }

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: dacpac_drop'
    inputs:
      ArtifactName: 'dacpac_drop'

trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    include:     
    #  You can generate this list using this linux command:
    #  find . -type d -name "*.DB" | sed -e 's/DB/DB\/\*/' | sed -e 's/.\//- /'
    - Certifications/src/NurseCron.Certifications.DB/*
    - Competencies/src/NurseCron.Competencies.DB/*
    - Employees/src/NurseCron.Employees.DB/*
    - HealthItems/src/NurseCron.HealthItems.DB/*
    - Schedules/src/NurseCron.Schedules.DB/*
    - Units/src/NurseCron.Units.DB/*


pr:
  branches:
    include:
    - master
  paths:
    include:
    - Certifications/src/NurseCron.Certifications.DB/*
    - Competencies/src/NurseCron.Competencies.DB/*
    - Employees/src/NurseCron.Employees.DB/*
    - HealthItems/src/NurseCron.HealthItems.DB/*
    - Schedules/src/NurseCron.Schedules.DB/*
    - Units/src/NurseCron.Units.DB/*

