version: '3'
services:
  db:
    build:
      context: .
      dockerfile: DB.Dockerfile
    ports:
    - "1433:1433"
  cert-api:
    build: MicroServices/Certifications/src/NurseCron.Certifications.api/.
    environment:
    - IdentityProvider=https://ikemtz.auth0.com/
    - IdentityAudiences=NRSRx-Local-Docker
    - OAuthClientId=qTiPFgac8zPm04HVwgACMp7h2YbZ3451
    - OAuthAppName=NRSRx-Local-Docker (Swagger Client)
    - InstrumentationKey=310823a1-7fc9-40fa-be72-06ab32952e85
    - SqlConnectionString=Data Source=db;Initial Catalog=NRSRx;User ID=sa;Password=SqlDockerRocks123!;
    - CorsOrigin=http://localhost:4200
    ports:
    - "81:80"
  comp-api:
    build: MicroServices/Competencies/src/NurseCron.Competencies.api/.
    environment:
    - IdentityProvider=https://ikemtz.auth0.com/
    - IdentityAudiences=NRSRx-Local-Docker
    - OAuthClientId=qTiPFgac8zPm04HVwgACMp7h2YbZ3451
    - OAuthAppName=NRSRx-Local-Docker (Swagger Client)
    - InstrumentationKey=310823a1-7fc9-40fa-be72-06ab32952e85
    - SqlConnectionString=Data Source=db;Initial Catalog=NRSRx;User ID=sa;Password=SqlDockerRocks123!;
    - CorsOrigin=http://localhost:4200
    ports:
    - "82:80"
  empl-api:
    build: MicroServices/Employees/src/NurseCron.Employees.api/.
    environment:
    - IdentityProvider=https://ikemtz.auth0.com/
    - IdentityAudiences=NRSRx-Local-Docker
    - OAuthClientId=qTiPFgac8zPm04HVwgACMp7h2YbZ3451
    - OAuthAppName=NRSRx-Local-Docker (Swagger Client)
    - InstrumentationKey=310823a1-7fc9-40fa-be72-06ab32952e85
    - SqlConnectionString=Data Source=db;Initial Catalog=NRSRx;User ID=sa;Password=SqlDockerRocks123!;
    - CorsOrigin=http://localhost:4200
    ports:
    - "83:80"
  hlth-api:
    build: MicroServices/HealthItems/src/NurseCron.HealthItems.api/.
    environment:
    - IdentityProvider=https://ikemtz.auth0.com/
    - IdentityAudiences=NRSRx-Local-Docker
    - OAuthClientId=qTiPFgac8zPm04HVwgACMp7h2YbZ3451
    - OAuthAppName=NRSRx-Local-Docker (Swagger Client)
    - InstrumentationKey=310823a1-7fc9-40fa-be72-06ab32952e85
    - SqlConnectionString=Data Source=db;Initial Catalog=NRSRx;User ID=sa;Password=SqlDockerRocks123!;
    - CorsOrigin=http://localhost:4200
    ports:
    - "84:80"
  ui:
    build: NRSRx.UI/nx/.
    ports:
    - "90:80"
